version: '3.8'
services:
  app:
    # build: .
    image: 1972akshay/rudderstack-catalogue-app:1.0
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/rudderstack
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
