openapi: 3.0.0
info:
  title: Rudderstack Data Catalog API
  version: 1.0.0
  description: Minimal API documentation for Tracking Plan endpoints

servers:
  - url: http://localhost:3000

paths:
  /api/v1/tracking-plans:
    get:
      summary: Get all tracking plans
      tags: [TrackingPlan]
      responses:
        "200":
          description: List of tracking plans
    post:
      summary: Create a new tracking plan
      tags: [TrackingPlan]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        "201":
          description: Tracking plan created
        "409":
          description: Duplicate tracking plan

  /api/v1/tracking-plans/{ref}:
    get:
      summary: Get a tracking plan by ref
      tags: [TrackingPlan]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Tracking plan found
        "404":
          description: Not found
    put:
      summary: Update a tracking plan by ref
      tags: [TrackingPlan]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Tracking plan updated
        "404":
          description: Not found
    delete:
      summary: Delete a tracking plan by ref
      tags: [TrackingPlan]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Tracking plan deleted
        "404":
          description: Not found

  /api/v1/tracking-plans/event:
    patch:
      summary: Upsert event(s) to a tracking plan
      tags: [TrackingPlan]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tracking_plan_id:
                  type: string
                events:
                  type: array
                  items:
                    type: object
      responses:
        "200":
          description: Event(s) upserted
        "404":
          description: Tracking plan not found

  /api/v1/events:
    get:
      summary: Get all events
      tags: [Event]
      responses:
        "200":
          description: List of events
    post:
      summary: Create a new event
      tags: [Event]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                description:
                  type: string
                validation:
                  type: object
      responses:
        "201":
          description: Event created
        "409":
          description: Duplicate event

  /api/v1/events/{ref}:
    get:
      summary: Get an event by ref
      tags: [Event]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event found
        "404":
          description: Not found
    put:
      summary: Update an event by ref
      tags: [Event]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Event updated
        "404":
          description: Not found
    delete:
      summary: Delete an event by ref
      tags: [Event]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event deleted
        "404":
          description: Not found

  /api/v1/properties:
    get:
      summary: Get all properties
      tags: [Property]
      responses:
        "200":
          description: List of properties
    post:
      summary: Create a new property
      tags: [Property]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                description:
                  type: string
                validation:
                  type: object
      responses:
        "201":
          description: Property created
        "409":
          description: Duplicate property

  /api/v1/properties/{ref}:
    get:
      summary: Get a property by ref
      tags: [Property]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Property found
        "404":
          description: Not found
    put:
      summary: Update a property by ref
      tags: [Property]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Property updated
        "404":
          description: Not found
    delete:
      summary: Delete a property by ref
      tags: [Property]
      parameters:
        - in: path
          name: ref
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Property deleted
        "404":
          description: Not found
